import type { Person } from "./PersonNode";
import type { Relationship } from "./RelationshipEditorModal";

// Sample family: The Smith Family Tree
export const sampleFamilyData = {
  people: [
    // Grandparents generation (top row, y=200)
    {
      id: "gf1",
      firstName: "William",
      lastName: "Smith",
      birthDate: "1925-03-15",
      deathDate: "2010-12-08",
      birthPlace: "Chicago, Illinois",
      deathPlace: "Miami, Florida",
      gender: "male" as const,
      profession: "Carpenter & WWII Veteran",
      isFounder: true,
      isDeceased: true,
      canvasX: 300,
      canvasY: 200,
      canvasWidth: 200,
      canvasHeight: 120,
      notes:
        "Veteran of World War II, worked as a carpenter for 40 years. Founded the Smith family carpentry business.",
    },
    {
      id: "gm1",
      firstName: "Mary",
      lastName: "Smith",
      middleName: "Elizabeth",
      birthDate: "1928-07-22",
      deathDate: "2015-04-30",
      birthPlace: "Detroit, Michigan",
      deathPlace: "Miami, Florida",
      gender: "female" as const,
      profession: "School Teacher",
      spouse: "William Smith",
      isDeceased: true,
      canvasX: 550,
      canvasY: 200,
      canvasWidth: 200,
      canvasHeight: 120,
      notes:
        "School teacher for 35 years, passionate about education and community service. Taught at Lincoln Elementary.",
    },
    {
      id: "gf2",
      firstName: "Robert",
      lastName: "Johnson",
      birthDate: "1930-11-10",
      birthPlace: "Boston, Massachusetts",
      gender: "male" as const,
      profession: "Computer Engineer",
      spouse: "Patricia Johnson",
      canvasX: 1100,
      canvasY: 200,
      canvasWidth: 200,
      canvasHeight: 120,
      notes:
        "Pioneer engineer who worked on early computer systems at IBM. Held 12 patents.",
    },
    {
      id: "gm2",
      firstName: "Patricia",
      lastName: "Johnson",
      nickname: "Patty",
      birthDate: "1932-05-18",
      birthPlace: "Portland, Oregon",
      gender: "female" as const,
      profession: "Artist & Community Organizer",
      spouse: "Robert Johnson",
      canvasX: 1350,
      canvasY: 200,
      canvasWidth: 200,
      canvasHeight: 120,
      notes:
        "Professional painter and community organizer. Her artwork is displayed in several local galleries.",
    },

    // Parents generation (middle row, y=450)
    {
      id: "f1",
      firstName: "James",
      lastName: "Smith",
      middleName: "William",
      birthDate: "1952-08-12",
      birthPlace: "Chicago, Illinois",
      gender: "male" as const,
      profession: "Software Architect",
      spouse: "Linda Smith",
      isFounder: true,
      canvasX: 425,
      canvasY: 450,
      canvasWidth: 200,
      canvasHeight: 120,
      notes: "Software architect, loves hiking and photography.",
    },
    {
      id: "m1",
      firstName: "Linda",
      lastName: "Smith",
      birthDate: "1955-02-28",
      birthPlace: "Boston, Massachusetts",
      gender: "female" as const,
      profession: "Pediatric Nurse",
      spouse: "James Smith",
      isFounder: true,
      canvasX: 675,
      canvasY: 450,
      canvasWidth: 200,
      canvasHeight: 120,
      notes: "Pediatric nurse, devoted mother of three.",
    },

    // Siblings (bottom left, y=700)
    {
      id: "c1",
      firstName: "Michael",
      lastName: "Smith",
      birthDate: "1978-06-15",
      birthPlace: "Denver, Colorado",
      gender: "male" as const,
      profession: "Marketing Director",
      spouse: "Amanda Smith",
      canvasX: 200,
      canvasY: 700,
      canvasWidth: 200,
      canvasHeight: 120,
      notes: "Marketing director, married with two children.",
    },
    {
      id: "c2",
      firstName: "Sarah",
      lastName: "Williams",
      birthDate: "1980-09-22",
      birthPlace: "Denver, Colorado",
      gender: "female" as const,
      profession: "Graphic Designer",
      spouse: "David Williams",
      canvasX: 650,
      canvasY: 700,
      canvasWidth: 200,
      canvasHeight: 120,
      notes: "Graphic designer, recently moved to Portland.",
    },
    {
      id: "c3",
      firstName: "David",
      lastName: "Smith",
      birthDate: "1983-12-03",
      birthPlace: "Denver, Colorado",
      gender: "male" as const,
      profession: "Medical Student",
      canvasX: 1000,
      canvasY: 700,
      canvasWidth: 200,
      canvasHeight: 120,
      notes: "Medical student, passionate about global health.",
    },

    // Spouses (positioned near their partners)
    {
      id: "s1",
      firstName: "Jennifer",
      lastName: "Smith",
      birthDate: "1979-04-18",
      gender: "female" as const,
      profession: "Elementary Teacher",
      spouse: "David Smith",
      canvasX: 1250,
      canvasY: 700,
      canvasWidth: 200,
      canvasHeight: 120,
      notes: "Teacher, loves cooking and gardening.",
    },
    {
      id: "s2",
      firstName: "Thomas",
      lastName: "Williams",
      birthDate: "1978-01-25",
      gender: "male" as const,
      profession: "Software Engineer",
      spouse: "Sarah Williams",
      canvasX: 450,
      canvasY: 700,
      canvasWidth: 200,
      canvasHeight: 120,
      notes: "Software engineer, plays guitar in a local band.",
    },

    // Next generation (bottom row, y=950)
    {
      id: "gc1",
      firstName: "Emma",
      lastName: "Smith",
      birthDate: "2005-03-10",
      gender: "female" as const,
      profession: "High School Student",
      canvasX: 100,
      canvasY: 950,
      canvasWidth: 180,
      canvasHeight: 110,
      notes: "High school student, interested in biology.",
    },
    {
      id: "gc2",
      firstName: "Liam",
      lastName: "Smith",
      birthDate: "2008-07-20",
      gender: "male" as const,
      profession: "Middle School Student",
      canvasX: 320,
      canvasY: 950,
      canvasWidth: 180,
      canvasHeight: 110,
      notes: "Middle school student, loves soccer and video games.",
    },
    {
      id: "gc3",
      firstName: "Olivia",
      lastName: "Williams",
      birthDate: "2010-11-12",
      gender: "female" as const,
      profession: "Elementary Student",
      canvasX: 540,
      canvasY: 950,
      canvasWidth: 180,
      canvasHeight: 110,
      notes: "Elementary student, enjoys drawing and dance.",
    },
  ] as Person[],

  relationships: [
    // Grandparent marriages
    {
      id: "r1",
      person1Id: "gf1",
      person2Id: "gm1",
      relationshipType: "spouse" as const,
      startDate: "1950-06-15",
      connectionColor: "#e11d48",
      connectionWidth: 3,
      notes: "Married for 60 years",
    },
    {
      id: "r2",
      person1Id: "gf2",
      person2Id: "gm2",
      relationshipType: "spouse" as const,
      startDate: "1953-09-12",
      connectionColor: "#e11d48",
      connectionWidth: 3,
      notes: "Married for 62 years",
    },

    // Parent-child relationships (grandparents to parents)
    {
      id: "r3",
      person1Id: "gf1",
      person2Id: "f1",
      relationshipType: "parent-child" as const,
      connectionColor: "#2563eb",
      connectionWidth: 2,
    },
    {
      id: "r4",
      person1Id: "gm1",
      person2Id: "f1",
      relationshipType: "parent-child" as const,
      connectionColor: "#2563eb",
      connectionWidth: 2,
    },
    {
      id: "r5",
      person1Id: "gf2",
      person2Id: "m1",
      relationshipType: "parent-child" as const,
      connectionColor: "#2563eb",
      connectionWidth: 2,
    },
    {
      id: "r6",
      person1Id: "gm2",
      person2Id: "m1",
      relationshipType: "parent-child" as const,
      connectionColor: "#2563eb",
      connectionWidth: 2,
    },

    // Parent marriage
    {
      id: "r7",
      person1Id: "f1",
      person2Id: "m1",
      relationshipType: "spouse" as const,
      startDate: "1977-05-20",
      connectionColor: "#e11d48",
      connectionWidth: 3,
      notes: "Married for over 45 years",
    },

    // Parent-child relationships (parents to children)
    {
      id: "r8",
      person1Id: "f1",
      person2Id: "c1",
      relationshipType: "parent-child" as const,
      connectionColor: "#2563eb",
      connectionWidth: 2,
    },
    {
      id: "r9",
      person1Id: "m1",
      person2Id: "c1",
      relationshipType: "parent-child" as const,
      connectionColor: "#2563eb",
      connectionWidth: 2,
    },
    {
      id: "r10",
      person1Id: "f1",
      person2Id: "c2",
      relationshipType: "parent-child" as const,
      connectionColor: "#2563eb",
      connectionWidth: 2,
    },
    {
      id: "r11",
      person1Id: "m1",
      person2Id: "c2",
      relationshipType: "parent-child" as const,
      connectionColor: "#2563eb",
      connectionWidth: 2,
    },
    {
      id: "r12",
      person1Id: "f1",
      person2Id: "c3",
      relationshipType: "parent-child" as const,
      connectionColor: "#2563eb",
      connectionWidth: 2,
    },
    {
      id: "r13",
      person1Id: "m1",
      person2Id: "c3",
      relationshipType: "parent-child" as const,
      connectionColor: "#2563eb",
      connectionWidth: 2,
    },

    // Sibling relationships
    {
      id: "r14",
      person1Id: "c1",
      person2Id: "c2",
      relationshipType: "sibling" as const,
      connectionColor: "#10b981",
      connectionWidth: 2,
    },
    {
      id: "r15",
      person1Id: "c2",
      person2Id: "c3",
      relationshipType: "sibling" as const,
      connectionColor: "#10b981",
      connectionWidth: 2,
    },
    {
      id: "r16",
      person1Id: "c1",
      person2Id: "c3",
      relationshipType: "sibling" as const,
      connectionColor: "#10b981",
      connectionWidth: 2,
    },

    // Marriages in current generation
    {
      id: "r17",
      person1Id: "c1",
      person2Id: "s1",
      relationshipType: "spouse" as const,
      startDate: "2003-08-15",
      connectionColor: "#e11d48",
      connectionWidth: 3,
    },
    {
      id: "r18",
      person1Id: "c2",
      person2Id: "s2",
      relationshipType: "spouse" as const,
      startDate: "2007-06-22",
      connectionColor: "#e11d48",
      connectionWidth: 3,
    },

    // Next generation parent-child relationships
    {
      id: "r19",
      person1Id: "c1",
      person2Id: "gc1",
      relationshipType: "parent-child" as const,
      connectionColor: "#2563eb",
      connectionWidth: 2,
    },
    {
      id: "r20",
      person1Id: "s1",
      person2Id: "gc1",
      relationshipType: "parent-child" as const,
      connectionColor: "#2563eb",
      connectionWidth: 2,
    },
    {
      id: "r21",
      person1Id: "c1",
      person2Id: "gc2",
      relationshipType: "parent-child" as const,
      connectionColor: "#2563eb",
      connectionWidth: 2,
    },
    {
      id: "r22",
      person1Id: "s1",
      person2Id: "gc2",
      relationshipType: "parent-child" as const,
      connectionColor: "#2563eb",
      connectionWidth: 2,
    },
    {
      id: "r23",
      person1Id: "c2",
      person2Id: "gc3",
      relationshipType: "parent-child" as const,
      connectionColor: "#2563eb",
      connectionWidth: 2,
    },
    {
      id: "r24",
      person1Id: "s2",
      person2Id: "gc3",
      relationshipType: "parent-child" as const,
      connectionColor: "#2563eb",
      connectionWidth: 2,
    },

    // Sibling relationships in next generation
    {
      id: "r25",
      person1Id: "gc1",
      person2Id: "gc2",
      relationshipType: "sibling" as const,
      connectionColor: "#10b981",
      connectionWidth: 2,
    },
  ] as Relationship[],
};
